title: Ryan's page
author: YellowDamage  
email: reule1@ocdsb.ca
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my website!

# social links
twitter_username: @YellowDamage
github_username:  @YellowDamage

show_excerpts: true # set to false to remove excerpts on the homepage
